version: '3'
services:
  web:
    image: dpodpryatov/ds:lab07
#    build: .
    ports:
      - 8080:8080

  nginx:
    image: "nginx:alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/var/www/web/templates
      - ./static:/var/www/web/static
    depends_on:
      - web
    ports:
      - 80:80
